p1:
    robot_ip: "172.16.1.2"
    server_ip: "141.3.53.152"
    robot_port: 1234
    gripper_port: 1235
p2:
    robot_ip: "172.16.2.2"
    server_ip: "141.3.53.152"
    robot_port: 4321
    gripper_port: 4322

